### ISSUE TITLE
Class attribute is stripped from list items

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/AztecEditor-iOS#984] opened 2018-06-18 10:41 UTC
When Aztec opens a gallery from Gutenberg and saves it's stripping the `class` attribute from each list item, breaking the gallery block.

It's turning this:

```
<!-- wp:gallery -->
<ul class="wp-block-gallery alignnone columns-1 is-cropped">
    <li class="blocks-gallery-item">
        <figure><img src="https://sandbox.koke.me/wp-content/uploads/2018/05/fullsizeoutput_52f7.jpeg" alt="" data-id="96" /></figure>
    </li>
</ul>
<!-- /wp:gallery -->
```

Into this:

```
<!-- wp:gallery -->
<ul class="wp-block-gallery alignnone columns-1 is-cropped">
  <li>
    <figure><img src="https://sandbox.koke.me/wp-content/uploads/2018/05/fullsizeoutput_52f7.jpeg" class="alignnone" data-id="96" alt=""></figure>
  </li>
</ul>
<!-- /wp:gallery -->
```

**Comment by diegoreymendez** [comment] 2018-06-19 01:48
Closing as this is a duplicate of https://github.com/wordpress-mobile/AztecEditor-iOS/issues/578.

I'll add the tag and extra details there.

**Closed by diegoreymendez** 2018-06-19 01:48 UTC
Labels: Gutenberg Compatibility
