### ISSUE TITLE
Lists are showing extra items

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/AztecEditor-iOS#640] opened 2017-07-21 15:04 UTC
As reported by @rachelmcr:

> A couple iOS users are reporting problems with the formatting of their lists in Aztec. One WordPress.com user in #205395-h gave this post as an example:
>
> [Parks in the central city](https://href.li/?https://gettingaroundsac.blog/2017/07/18/parks-in-the-central-city/)
>
> I copied that content into a test post and I’m seeing blank list items and extra br tags in Aztec:
>
> ![2017-07-21-13-28-51](https://user-images.githubusercontent.com/1836005/28469412-876727b8-6e0c-11e7-8b84-760c049ff308.png)
>
> ![2017-07-21-13-29-17](https://user-images.githubusercontent.com/1836005/28469436-9bf54142-6e0c-11e7-9c31-7abb81c1ecb9.png)
>
> I created a test post in Calypso with a 3-item numbered list on my test blog ... And I’m seeing a similar issue with extra list items in visual mode and extra br tags when I opened the post in Aztec.

**Comment by jleandroperez** [comment] 2017-07-24 14:38
Closing since this is an integration issue. [Addressing Here](https://github.com/wordpress-mobile/WordPress-iOS/issues/7598).

Thanks Diego!

**Closed by jleandroperez** 2017-07-24 14:38 UTC
Labels: [Priority] High, [Type] Bug

**Comment by designsimply** [comment] 2017-08-02 02:12
Tested and confirmed fixed using the steps from https://github.com/wordpress-mobile/WordPress-iOS/pull/7599.

<img alt="img_1398" src="https://user-images.githubusercontent.com/1119271/28854637-a339654a-76f5-11e7-8440-874d49bc4ac7.PNG" width="270" />
<sup>Tested with madefortesting.com running WP 4.9 and JP 5.2 hosted at Bluehost using iPhone 6S, iOS 10.3.3, WPiOS 8.2.0.20170731.</sup>

Note: not sure the test is enough? Did I test well enough by copying the code from https://github.com/wordpress-mobile/WordPress-iOS/pull/7599 into a post on the web and then viewing that same post in WPiOS 8.2.0.20170731?

**Comment by jleandroperez** [comment] 2017-08-03 13:05
@designsimply Yup, that test was more than enough!! thanks for helping us out!!
