### ISSUE TITLE
Image alignment lost for posts edited with WPiOS

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/AztecEditor-iOS#890] opened 2018-01-16 23:24 UTC
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Blog Posts > Add.
1. Create a post with a centered thumbnail-sized image.
1. Publish and view the post to verify the image looks centered.
1. Open the same post in WPiOS and add any text to the body of the post and save changes.
1. View the post and compare the image alignment for the image in the editor versus the front end.

<strong>Result:</strong> image alignment is lost after editing a post with centered images in WPiOS.

I noticed the class `aligncenter` is missing in WPiOS as soon as the post is opened for editing.

Original post created via the web:

<img width="1280" alt="screen shot 2018-01-16 at tue jan 16 2 45 09 pm" src="https://user-images.githubusercontent.com/1119271/35016990-d106f7e0-facf-11e7-97f5-ebe1f2cb33bb.png">
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11714 using Firefox 57.0.3 on macOS 10.13.2.</sup>

Post as soon as it is opened in WPiOS:

<img alt="img_1779" src="https://user-images.githubusercontent.com/1119271/35017019-e70ca38c-facf-11e7-9d0b-895390024f7c.PNG" width="270" />
<sup>iPhone 6S, iOS 11.2.1, WPiOS 9.1</sup>

##### Tested on iPhone 6S, iOS 11.2.1, WPiOS 9.1

/hat tip @RyanRhoten for raising the issue in #triage on Slack (internal ref: 894502-zen).

**Comment by diegoreymendez** [comment] 2018-01-17 12:57
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/8442

Closing here.

**Comment by SergioEstevao** [comment] 2018-02-07 10:12
@diegoreymendez I'm reopening this because the problem is our image serialiser in Aztec.

**Closed** 2018-02-13 09:29 UTC
Labels: [Type] Bug
