### ISSUE TITLE
Underline not visible part of the underline text

### ISSUE THREAD

**Issue by arisun** [wordpress-mobile/AztecEditor-iOS#616] opened 2017-07-14 15:33 UTC
### Expected behavior
Underline should be visible through out text.

### Actual behavior
Underline visible in part of the text.

### Steps to reproduce the behavior
Insert random text where the first character of the text height is less than the remaining characters available in the text. i.e. (Jjjjjjj)

##### Tested on [device], iOS [version]
iPhone 5S, 10.3

![screenshot_underline](https://user-images.githubusercontent.com/855955/28218942-d38de7d8-68d7-11e7-9f52-3e2b588ac88a.png)

**Comment by diegoreymendez** [comment] 2017-07-14 16:47
Small note when tackling this: we should evaluate if this is an issue in Aztec, or just an issue with the font that Aztec uses.

**Comment by SergioEstevao** [comment] 2017-07-18 09:13
I've tested this and the undeline is actually draw but it's on the back of the characters!!! if you put a space between the j on the example above you will see the underline there.

**Comment by SergioEstevao** [comment] 2017-07-18 09:16
I've also tested this with a regular text view using the default font (Arial) and the same happens so I think this a bug on Apple Core Text drawing.

**Comment by diegoreymendez** [comment] 2017-07-18 13:57
Closing this as it's an issue with either the font or CoreText (and not a bug in Aztec).

**Closed by diegoreymendez** 2017-07-18 13:57 UTC
Labels: [Type] Bug
