### ISSUE TITLE
Paragraphs/Line Breaks are missing

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/AztecEditor-iOS#274] opened 2017-02-15 14:21 UTC
In Calypso, hitting Enter creates a paragraph break with space between paragraphs.
When I open that post in Aztec, the paragraph breaks are completely gone. There aren’t any line breaks between the different paragraphs I created in Calypso:

**Comment by diegoreymendez** [comment] 2017-02-26 14:58
Isn't this ticket a duplicate of #64?

**Comment by diegoreymendez** [comment] 2017-06-16 17:00
This is no longer an issue since the DOM structure removal.

**Closed by diegoreymendez** 2017-06-16 17:00 UTC
Labels: [Type] Bug
