### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by musicode** [wordpress-mobile/AztecEditor-iOS#298] opened 2017-02-18 08:33 UTC
Aztec dont support chinese content(set and get is wrong)

bold and italic is not ok

**Comment by musicode** [comment] 2017-02-20 01:37
hi, anyone can help me?

**Comment by musicode** [comment] 2017-02-21 11:30
anyone could test by "哈哈哈"

**Comment by diegoreymendez** [comment] 2017-02-22 13:32
Hi @musicode.  I've just tried the string you provided and it seems to be working fine when switching to HTML mode, and back to visual.

Can you check if you're still having issues in the latest code form `develop`, and if so: could you provide steps to reproduce the issue you're seeing?

Thank you!

**Comment by musicode** [comment] 2017-02-22 14:20
![](http://7xr7e0.com1.z0.glb.clouddn.com/QQ20170222-222311@2x.png)


`italic` is not work. and the html is as below:

![](http://7xr7e0.com1.z0.glb.clouddn.com/QQ20170222-222323@2x.png)

`&#x54c8` is not `哈`，is something wrong?

**Comment by diegoreymendez** [comment] 2017-02-22 14:39
@musicode - I understand.  We'll be reviewing this in the upcoming releases of Aztec to offer better support for Chinese text, although there are higher priority items we'll first need to deal with.

As additional information `&#x54c8` is an encoded form of displaying `哈`, which while annoying for the purpose of HTML editing, should not cause any issues in visual mode.

**Comment by musicode** [comment] 2017-02-22 14:47
thank you!

**Comment by diegoreymendez** [comment] 2017-02-24 19:02
Unassigned for the time being, until we can focus on international support.

**Comment by diegoreymendez** [comment] 2017-07-20 13:21
This issue will be fixed in #632, which unifies the same fix for all languages with non-latin alphabets.

**Closed by diegoreymendez** 2017-07-20 13:21 UTC
Labels: [Priority] Low, [Type] Bug
